name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
            ${{ github.repository_owner }}/adc-certupdater-letsencrypt:latest
            ${{ github.repository_owner }}/adc-certupdater-letsencrypt:$(date +%s)
            ghcr.io/${{ github.repository_owner }}/adc-certupdater-letsencrypt:latest
            ghcr.io/${{ github.repository_owner }}/adc-certupdater-letsencrypt:$(date +%s)
